org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=1.21.10
loader_version=0.18.4
loom_version=1.14-SNAPSHOT

mod_version=1.3.0+mc1.21.10-fabric
maven_group=com.coolerpromc
archives_base_name=archerythings

fabric_api_version=0.137.0+1.21.10
owo_version=0.12.24+1.21.9
accessories_version=1.4.3-beta+1.21.10